version: '2'

services:
   db:
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: CHANGEME
       # MYSQL_DATABASE: 
       # MYSQL_USER: 
       # MYSQL_PASSWORD: CHANGEME
       MYSQL_ROOT_HOST: "%"
     networks:
       - mysql
   web:
     image: nginx:latest
     restart: always
     depends_on:
       - php
       - db
     ports:
       - "80:80"
       - "443:443"
     networks:
       - php
     volumes:
       - ./code:/usr/share/nginx/html/
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./site.conf:/etc/nginx/conf.d/default.conf:ro
   php:
    build: ./php
    restart: always
    depends_on:
      - db
    networks:
      - php
      - mysql
    volumes:
        - ./code:/usr/share/nginx/html/
        
networks:
   php:
   mysql:
